cpanel/urls.py
from django.urls import path

from . import views

app_name = 'cpanel'
urlpatterns = [
    path('', views.index, name='index'), 
    path('gcam_view',	views.gcam_view,	name='gcam_view'),
    path('video_play',	views.video_play, 	name='video_play'),
    path('video_record',views.video_record, 	name='video_record'),
    path('setup',	views.setup, 		name='setup'),
    path('setup_update',views.setup_update, 	name='setup_update'),
    path('LED_control',	views.LED_control, 	name='LED_control'),
    path('acc_plot',	views.acc_plot, 	name='acc_plot'),

]

gcam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('cpanel.urls')),
    path('admin/', admin.site.urls),
]

cpanel/models.py
from django.db import models

# Create your models here.

class Acc1(models.Model):
    measure_time = models.CharField(max_length=16,null=False)
    rmsACC = models.FloatField()
    fileUploaded = models.BooleanField(default=False)

class Acc2(models.Model):
    measure_time = models.CharField(max_length=16,null=False)
    rmsACC = models.FloatField()
    fileUploaded = models.BooleanField(default=False)
    
class Acc3(models.Model):
    measure_time = models.CharField(max_length=16)
    rmsACC = models.FloatField()
    fileUploaded = models.BooleanField(default=False)
    
class Event(models.Model):
    measure_time = models.CharField(max_length=16)
    

class SystemState(models.Model):
    acc_threshold = models.FloatField()
    icam = models.IntegerField()
    Time_gcUploaded_acc1 = models.DateTimeField(null=True)
    Time_gcUploaded_acc2 = models.DateTimeField(null=True)
    Time_gcUploaded_acc3 = models.DateTimeField(null=True)
    Time_gcUploaded_tmp1 = models.DateTimeField(null=True)
    Time_gcUploaded_tmp2 = models.DateTimeField(null=True)
    Time_gcUploaded_tmp3 = models.DateTimeField(null=True)

cpanel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
import subprocess

import time
import logging
import socket_client
import datetime

from cpanel.models import Acc1, Acc2, Acc3, Event, SystemState

import guymon
import os

from django.shortcuts import redirect
import subprocess
import sys


logging.basicConfig(stream=sys.stdout)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
 


def stop_streaming():
    # start the server                                                                                                                          
    MyOut = subprocess.Popen(['/usr/bin/sudo','systemctl','stop','64_video_streaming.service'],
                         stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
    stdout,stderr = MyOut.communicate()
    return



def index(request):
    global latest_video_file

    stop_streaming()
    
    # return HttpResponse("Hello, world. You're at the polls index.")
    requests = 'get,icam;get,time;get,switch;get,state;get,astate;get,afile;get,arms;get,threshold;get,mem;get,disk;get,volt;get,pwrLED;'
    #           0        1        2          3         4          5         6        7             8       9        10       11
    logger.debug('socket_client.request  {}...'.format(requests))
    responses = socket_client.request(requests)
    if responses:
        response_list = responses.split(';')
        icam = int(response_list[0])
        time = datetime.datetime.fromtimestamp(int(response_list[1])).strftime('%Y-%m-%d %H:%M:%S')
        switch = int(response_list[2])
        state = int(response_list[3])
        acc_state = [int(i) for i in response_list[4].split(',')]
        acc_file  = response_list[5].split(',')
        acc_rms = response_list[6].split(',')
        acc_threshold = [float(thr) for thr in response_list[7].split(',')]
        mem = response_list[8].split(',')
        volt = response_list[10]
        disk = response_list[9].split(',')
        pwrLED = 'checked' if 'on'in response_list[11] else 'unchecked'


    else:
        icam = 0
        time = 'unknown'
        switch = 'unknown'
        state = 'unknown'
        acc_state = [None,None,None]
        acc_file = [None,None,None]
        acc_rms = ['',None,'',None,'',None]
        acc_threshold = [None,None,None]
        mem = [None,None]
        volt = 0
        disk = [None,None]
        pwrLED = 'unchecked'
        latest_accFiles = ['','','']

    if icam:
    # Database interaction: RMS
        logger.debug('*********************')
        logger.debug('acc_rms[0]={}'.format(acc_rms[0]))

        if acc_rms[0]:
            acc1_last = Acc1.objects.last()
            logger.debug('acc1_last={}'.format(acc1_last))
            if not acc1_last:
                logger.debug('acc1_last None')
                Acc1(measure_time = acc_rms[0],rmsACC=float(acc_rms[1])).save()
            elif acc_rms[0] > acc1_last.measure_time:
                logger.debug('acc_rms[0]>acc1_last.measure_time:{}>{}'.format(acc_rms[0],acc1_last.measure_time))
                Acc1(measure_time = acc_rms[0],rmsACC=float(acc_rms[1])).save()
        if acc_rms[2]:
            acc2_last = Acc2.objects.last()
            if not acc2_last:
                Acc2(measure_time = acc_rms[2],rmsACC=float(acc_rms[3])).save()
            elif acc_rms[2] > acc2_last.measure_time:
                Acc2(measure_time = acc_rms[2],rmsACC=float(acc_rms[3])).save()
        if acc_rms[4]:
            acc3_last = Acc3.objects.last()
            if not acc3_last:
                Acc3(measure_time = acc_rms[4],rmsACC=float(acc_rms[5])).save()
            elif acc_rms[4] > acc3_last.measure_time:
                Acc3(measure_time = acc_rms[4],rmsACC=float(acc_rms[5])).save()

        logger.debug('*************************')
        logger.debug('* acc_rms = [{}, {}]'.format(acc_rms[0], acc_rms[1]))    
        logger.debug('*************************')        

        # Database interaction: File
        for inode in range(3):
            if acc_file[inode]:
                if inode ==0:
                    logger.debug('acc_file[inode]={}'.format(acc_file[inode]))
                    acci = Acc1.objects.filter(measure_time=acc_file[inode])
                elif inode==1:
                    acci = Acc2.objects.filter(measure_time=acc_file[inode])
                elif inode==2:
                    acci = Acc3.objects.filter(measure_time=acc_file[inode])
                if len(acci):
                    acci_ = acci[0]
                    if not acci_.fileUploaded:
                        acci_.fileUploaded = True
                        acci_.save()
        logger.debug('*************************')
        logger.debug('* acc_file = [{}, {},{}]'.format(acc_file[0], acc_file[1], acc_file[2]))    
        logger.debug('*************************')        

        latest_accFiles = [ Acc1.objects.filter(fileUploaded=True).last().measure_time,
                            Acc2.objects.filter(fileUploaded=True).last().measure_time,
                            Acc3.objects.filter(fileUploaded=True).last().measure_time]
        logger.debug('*************************')
        logger.debug('* acc_file = [{}, {},{}]'.format(acc_file[0], acc_file[1], acc_file[2]))    
        logger.debug('*************************')        
        logger.debug('pwrLED={}'.format(pwrLED))


        # SystemStates
        sysState = SystemState.objects.last()
        if not sysState: # initialise
            SystemState(icam=icam).save()
        else: # update if different
            if icam != sysState.icam:
                sysState.icam = icam
                sysState.save()

    latest_event = Event.objects.last()
    if not latest_event:
        latest_videoFile = 'None'
    else:
        latest_videoFile = 'gcam{}-{}.mp4'.format(icam,latest_event.measure_time)

    for i in range(3):
        if acc_rms[2*i]:
            already_captured=Event.objects.filter(measure_time=acc_rms[2*i])
            if float(acc_rms[2*i+1]) > acc_threshold[i] and not already_captured:
                return redirect('/video_record?timestamp={}'.format(acc_rms[2*i]))

    contexts = {'icam':icam, 'time':time, 'switch':switch, 'state':state, \
                'acc_state':acc_state,'acc_file':acc_file, \
                'acc_rms':acc_rms, 'acc_threshold': acc_threshold, \
                'mem':mem, 'disk':disk, 'volt':volt, 'pwrLED':pwrLED, \
    		'latest_accFiles':latest_accFiles, 'latest_videoFile':latest_videoFile}

    logger.debug('socket_client.request done...')
         
    return render(request,'cpanel/index.html',contexts)


def video_play(request):

    try:
        filename = request.GET['filename']
        latest_videoFile = 'cpanel/video/{}'.format(filename)
    except:
        try:
            timestamp = request.GET['timestamp']
        except:
            timestamp = Event.objects.last().measure_time
        icam = SystemState.objects.last().icam
        latest_videoFile = 'cpanel/video/gcam{}-{}.mp4'.format(icam,timestamp)
        
    contexts = {'latest_videoFile':latest_videoFile}
    
    return render(request,'cpanel/video_play.html',contexts)

def gcam_view(request):

    # start the server
    MyOut = subprocess.Popen(['/usr/bin/sudo','systemctl','start','64_video_streaming.service'], 
                         stdout=subprocess.PIPE, 
                         stderr=subprocess.STDOUT)
    stdout,stderr = MyOut.communicate()

    # move to the streaming server address
    contexts={}
    return render(request,'cpanel/gcam_view.html',contexts)
    

def setup(request):

    requests = 'get,threshold;'
    logger.debug('socket_client.request  {}...'.format(requests))
    responses = socket_client.request(requests)
    if responses:
        response_list = responses.split(';')
        threshold_1 = response_list[0].split(',')[0]
        threshold_2 = response_list[0].split(',')[1]
        threshold_3 = response_list[0].split(',')[2]
    else:
        threshold_1 = 'unknown'
        threshold_2 = 'unknown'
        threshold_3 = 'unknown' 
    
    contexts = {'acc_threshold': [threshold_1, threshold_2, threshold_3]}
    return render(request,'cpanel/setup.html',contexts)

def setup_update(request):

    thres = [request.POST['acc_threshold_1'],
             request.POST['acc_threshold_2'],
             request.POST['acc_threshold_3']]
    requests = 'set,threshold,{},{},{}'.format(thres[0],thres[1],thres[2])
    logger.debug('socket_client.request  {}...'.format(requests))
    responses = socket_client.request(requests)
        
    contexts = {'acc_threshold':thres}
    return render(request,'cpanel/setup_update.html',contexts)

def LED_control(request):

    try:
        if request.POST['pwrLED'] in 'on':
            pwrLED = True
    except:
        pwrLED = False
        
    if pwrLED:
        contexts = {'pwrLED':'on'}
        requests = 'set,pwrLED,on;'
    else:
        contexts = {'pwrLED':'off'}
        requests = 'set,pwrLED,off;'
        
    logger.debug('pwrLED={}'.format(pwrLED))
        
    logger.debug('socket_client.request  {}...'.format(requests))
    responses = socket_client.request(requests)
    
    return render(request,'cpanel/LED_control.html',contexts)


def acc_plot(request):

    
    filename = 'gcam{}-acc{}-acc-{}'.format(request.GET['icam'],request.GET['iacc'],request.GET['timestamp'])
    go = guymon.guymon()
    guymon.download(filename)
    go.load('data/'+filename)
    go.genPlots('cpanel/static/cpanel/img/')
    go.genPlots('static/cpanel/img/')
    
    contexts = {'filename':filename}
    
    return render(request,'cpanel/acc_plot.html',contexts)

def video_record(request):

    try:
        timestamp = request.GET['timestamp']
    except:
        timestamp = datetime.datetime.now().strftime('%Y-%m%d-%H%M%S')
    Event(measure_time=timestamp).save()
    icam = SystemState.objects.last().icam

cpanel/templates/cpanel/LED_control.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
    
  </head>
  <body>

    Setting pwrLED={{pwrLED}}...

  <script>
       setTimeout(function(){
           window.location.href = 'http://'.concat(window.location.hostname);
       }, 1000);
  </script>

  </body>
</html>

cpanel/templates/cpanel/acc_plot.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
  </head>
  <body>
    <!--<h2>{{filename}}</h2>-->

    {{th_plot}}<br>
    {{psd_plot}}<br>
    
    {% load static %}
    <img src="{% static 'cpanel/img/th01.png' %}" width=100%>
    <img src="{% static 'cpanel/img/psd01.png' %}" width=100%>
    
    
  </body>
</html>

cpanel/templates/cpanel/gcam_view.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <style>
      body {
          font-family: Arial;
      }
    </style>
    
  </head>
  <body>
    Starting Camera Streaming Server...
    <script>
      setTimeout(function(){
	  //window.location.href = 'http://dev1.local:8001/';
	  var target = "http://".concat(window.location.hostname,":8001/");
	  //window.alert(target);
	  window.location.href = target;
      }, 2000);
      </script>
   
  </body>
</html>

cpanel/templates/cpanel/index.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
-->
    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
<!--    <link rel="stylesheet" href="wiki-mobile.css"> -->
    <meta http-equiv="refresh" content="10">
  

    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
    <!-- slider switch -->
    <style>
      .switch {
	  position: relative;
	  display: inline-block;
	  width: 60px;
	  height: 34px;
	  vertical-align: moddle;
      }

      .slider {
	  position: absolute;
	  cursor: pointer;
	  top: 0;
	  left: 0;
	  right: 0;
	  bottom: 0;
	  background-color: #ccc;
	  -webkit-transition: .4s;
	  transition: .4s;
      }

      .slider:before {
	  position: absolute;
	  content: "";
	  height: 26px;
	  width: 26px;
	  left: 4px;
	  bottom: 4px;
	  background-color: white;
	  -webkit-transition: .4s;
	  transition: .4s;
      }

      input:checked + .slider {
	  background-color: #2196F3;
      }

      input:focus + .slider {
	  box-shadow: 0 0 1px #2196F3;
      }

      input:checked + .slider:before {
	  -webkit-transform: translateX(26px);
	  -ms-transform: translateX(26px);
	  transform: translateX(26px);
      }

      /* Rounded sliders */
      .slider.round {
	  border-radius: 34px;
      }

      .slider.round:before {
	  border-radius: 50%;
      }
      [type="checkbox"]
      {
	  vertical-align:middle;
      }
    </style>
    
  </head>
  <body>
    <h2>Guy Monitoring Setup</h2>

    <table class="tg">
      <tr>
      	<td class="tg-0lax">
	  <b>CAM{{icam}}</b>
	</td>
      </tr>
      <tr>
	<td>
	  <form action="{% url 'cpanel:LED_control' %}" method="post" style="margin: 0; padding: 0;">
	    {% csrf_token %}
	    &emsp;<a href="/gcam_view">Live-View</a>
		<label for="x">&emsp;&emsp;&emsp;Infrared LED On/Off: </label><input style="display: inline;" type="checkbox" {{pwrLED}} name="pwrLED" onchange="this.form.submit();" id="x" />
	    </form>
	</td>
      </tr>

      <tr>
	<td class="tg-0lax">
	  &emsp;Latest Video: <a href="video_play?filename={{latest_videoFile}}">{{latest_videoFile}}</a>
	</td>
      </tr>

      <tr>
	<td class="tg-c3ow">
	  <b>ACC[1-3]</b>
	</td>
      </tr>
      <tr>
	<td class="tg-0lax">
	  &emsp;State: [{{acc_state.0}},{{acc_state.1}},{{acc_state.2}}]<sup>1</sup>,&ensp;RMS: [{{acc_rms.1}}, {{acc_rms.3}}, {{acc_rms.5}}] (g)
	</td>
      </tr>
      <tr>
	<td>
	  &emsp;Latest files:<br>
	  &emsp;&emsp;<a href="{% url 'cpanel:acc_plot' %}?icam={{icam}}&iacc=1&timestamp={{latest_accFiles.0}}">gcam{{icam}}-acc1-acc-{{latest_accFiles.0}}</a><br>
	  &emsp;&emsp;<a href="{% url 'cpanel:acc_plot' %}?icam={{icam}}&iacc=2&timestamp={{latest_accFiles.1}}">gcam{{icam}}-acc2-acc-{{latest_accFiles.1}}</a><br>
	  &emsp;&emsp;<a href="{% url 'cpanel:acc_plot' %}?icam={{icam}}&iacc=3&timestamp={{latest_accFiles.2}}">gcam{{icam}}-acc3-acc-{{latest_accFiles.2}}</a>
	</td>
      </tr>
            
      <tr>
	<td class="tg-c3ow">
	  <b>CTLR</b><sup>S{{state}}</sup>
	</td>
      </tr>
      <tr>
	<td class="tg-0lax">
	  &emsp;Acc-Thresholds: <a href="{% url 'cpanel:setup' %}">{{acc_threshold}}</a> (g)
	</td>
      </tr>
      <tr>
	<td class="tg-0lax">
	  &emsp;GPS Time: {{time}} (UTC)
	</td>
      </tr>
      <tr>
	<td class="tg-0lax">
	  &emsp;Mem: {{mem.0}}%/{{mem.1}}<sup>2</sup>,&ensp;Disk: {{disk.0}}%/{{disk.1}}%<sup>3</sup>,&ensp;Bat. {{volt}}V
	</td>
      </tr>      
    </table>
    1) 1=wake-up, 2=measure, 3=sleep<br>
    2) memory used: Heap (%)/Stack-Size<br>
    3) disk used: Flash(%)/SD-Card(%)

  </body>
</html>

cpanel/templates/cpanel/setup.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
    
  </head>
  <body>
    <h2>Accelerometer Threshold Values</h2>
    <form action="{% url 'cpanel:setup_update' %}" method="post">
      {% csrf_token %}
      <label for="acc_threshold_1">ACC1: </label>
      <input type="text" name="acc_threshold_1" value="{{acc_threshold.0}}"><br>
      <label for="acc_threshold_2">ACC2: </label>
      <input type="text" name="acc_threshold_2" value="{{acc_threshold.1}}"><br>
      <label for="acc_threshold_3">ACC3: </label>
      <input type="text" name="acc_threshold_3" value="{{acc_threshold.2}}"><br>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

cpanel/templates/cpanel/setup_update.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
    
  </head>
  <body>
    Acc_threshold values are updated to [{{acc_threshold.0}}, {{acc_threshold.1}}, {{acc_threshold.2}}] ...
  <script>
       setTimeout(function(){
           window.location.href = 'http://'.concat(window.location.hostname);
       }, 1000);
  </script>
  
  </body>
</html>

cpanel/templates/cpanel/video_play.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  

    <style>
      table, th, td {
	  border: 1px solid black;
	  border-collapse: collapse;
      }
      body {
          font-family: Arial;
      }
      .center { margin: 0 auto; width: 100%; }
    </style>
    
  </head>
  <body>
    <a href="/">Back to Main Page</a><br>

				   
    {% load static %}
   
    <video class="center" src="{% static latest_videoFile %}" height="90%" autoplay type="video/mp4"  playsinline muted controls="false">
	Your browser does not support HTML video.
    </video>
  </body>
</html>

cpanel/templates/cpanel/video_record.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Guy Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
 
      h1 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 25px;
      }
      h2 {
	  text-align: center;
	  font-family: Arial;
	  font-size: 20px;
      }
      table {
	  border-collapse: collapse;
	  width: 100%;
      }

      th, td {
	  font-weight: normal;
	  padding: 8px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  border-top: 1px solid #ddd;
      }
      body {
	  font-family: Arial;
      }
    </style>
   
  </head>
  <body>
    Recording video for 10 seconds...
     <script>
       setTimeout(function(){
          //window.location.href = 'http://dev1.local:8000/cpanel';
   	  var target = "http://".concat(window.location.hostname);
	  window.location.href = target;
       }, 11000);
  </script>
  </body>
</html>